apiVersion: v1
kind: Service
metadata:
  name: lspan-application-http
spec:
  type: NodePort
  selector:
    app: lspan-application-http
  ports:
    - name: http
      port: 80
      targetPort: 8080
