kind: Service
apiVersion: v1
metadata:
  name: lspan-application-http
spec:
  type: LoadBalancer
  selector:
    app: lspan-application-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
